// Code generated by Kitex v0.9.1. DO NOT EDIT.
package itemcenter

import (
	server "github.com/cloudwego/kitex/server"
	itemcenter "go_code/seckill-service/rpc/kitex_gen/itemcenter"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler itemcenter.Itemcenter, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler itemcenter.Itemcenter, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
